name: Deploy React Site

on:
  push:
    branches: ["gh-pages"] # Replace with your default branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create CNAME file
        run: echo "bbdr.tech" > ./dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # IMPORTANT: Use 'dist' for Vite or 'build' for Create React App
          path: './dist' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
